-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 : OUT STD_LOGIC_VECTOR (17 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_207 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_207_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_208 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_208_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_221 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_221_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_222 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_222_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_223 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_223_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_224 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_224_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_225 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_225_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_226 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_226_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_227 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_227_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_228 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_228_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_229 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_229_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_230 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_230_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_231 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_231_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_i : IN STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_o : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_232 : OUT STD_LOGIC_VECTOR (17 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_232_ap_vld : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_ce0 : STD_LOGIC;
    signal p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_we0 : STD_LOGIC;
    signal p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_ce0 : STD_LOGIC;
    signal p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_we0 : STD_LOGIC;
    signal p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (17 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_we0,
        d0 => p_read,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_we0,
        d0 => p_read1,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_we0,
        d0 => p_read2,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_we0,
        d0 => p_read3,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_we0,
        d0 => p_read4,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_we0,
        d0 => p_read5,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_we0,
        d0 => p_read6,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_we0,
        d0 => p_read7,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_we0,
        d0 => p_read8,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_we0,
        d0 => p_read9,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_q0);

    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_ce0,
        we0 => p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_we0,
        d0 => p_read10,
        q0 => p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_q0);

    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_U : component myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_12u_config5_s_void_pooling2d_cl_sfYi
    generic map (
        DataWidth => 18,
        AddressRange => 51,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_32,
        ce0 => p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_ce0,
        we0 => p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_we0,
        d0 => p_read11,
        q0 => p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_ce)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_ce)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_const_logic_0 = ap_ce))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_ce0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_we0 <= ap_const_logic_1;
        else 
            p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_207 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_207_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_207_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_207_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_208 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_208_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_208_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_208_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_i, void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_i, p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_o <= p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_219_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_i, p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_o <= p_ZZN4nnet12pooling2d_clINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_220_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_221 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_221_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_221_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_221_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_222 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_222_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_222_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_222_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_223 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_223_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_223_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_223_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_224 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_224_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_224_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_224_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_225 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_225_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_225_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_225_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_226 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_226_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_226_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_226_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_227 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_227_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_227_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_227_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_228 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_228_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_228_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_228_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_229 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_229_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_229_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_229_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_230 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_230_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_230_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_230_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_231 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_231_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_231_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_231_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_232 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_232_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_232_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_232_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_o_assign_proc : process(ap_CS_fsm_state1, p_read, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_o <= p_read;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_233_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_o_assign_proc : process(ap_CS_fsm_state1, p_read1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_o <= p_read1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_234_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_o_assign_proc : process(ap_CS_fsm_state1, p_read2, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_o <= p_read2;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_235_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_o_assign_proc : process(ap_CS_fsm_state1, p_read3, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_o <= p_read3;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_236_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_o_assign_proc : process(ap_CS_fsm_state1, p_read4, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_o <= p_read4;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_237_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_o_assign_proc : process(ap_CS_fsm_state1, p_read5, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_o <= p_read5;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_238_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_o_assign_proc : process(ap_CS_fsm_state1, p_read6, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_o <= p_read6;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_239_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_o_assign_proc : process(ap_CS_fsm_state1, p_read7, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_o <= p_read7;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_240_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_o_assign_proc : process(ap_CS_fsm_state1, p_read8, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_o <= p_read8;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_241_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_o_assign_proc : process(ap_CS_fsm_state1, p_read9, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_o <= p_read9;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_242_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_o_assign_proc : process(ap_CS_fsm_state1, p_read10, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_o <= p_read10;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_243_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_o_assign_proc : process(ap_CS_fsm_state1, p_read11, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_o <= p_read11;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_244_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_218_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_217_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_216_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_215_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_214_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_213_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_212_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_211_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_210_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi18ELi8EL9ap_q_mode5EL9ap_209_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_8_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_9_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_12u_0_line_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
