-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_18u_array_ap_fixed_18_8_5_3_0_18u_relu_config8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer7_out_dout : IN STD_LOGIC_VECTOR (665 downto 0);
    layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    layer7_out_empty_n : IN STD_LOGIC;
    layer7_out_read : OUT STD_LOGIC;
    layer8_out_din : OUT STD_LOGIC_VECTOR (323 downto 0);
    layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    layer8_out_full_n : IN STD_LOGIC;
    layer8_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_18u_array_ap_fixed_18_8_5_3_0_18u_relu_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_49 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001001";
    constant ap_const_lv32_4A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001010";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_93 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010011";
    constant ap_const_lv32_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010100";
    constant ap_const_lv32_B8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111000";
    constant ap_const_lv32_B9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111001";
    constant ap_const_lv32_DD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011101";
    constant ap_const_lv32_DE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011110";
    constant ap_const_lv32_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000010";
    constant ap_const_lv32_103 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000011";
    constant ap_const_lv32_127 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100111";
    constant ap_const_lv32_128 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101000";
    constant ap_const_lv32_14C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001100";
    constant ap_const_lv32_14D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001101";
    constant ap_const_lv32_171 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110001";
    constant ap_const_lv32_172 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110010";
    constant ap_const_lv32_196 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010110";
    constant ap_const_lv32_197 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010111";
    constant ap_const_lv32_1BB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111011";
    constant ap_const_lv32_1BC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111100";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1E1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100001";
    constant ap_const_lv32_205 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000101";
    constant ap_const_lv32_206 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000110";
    constant ap_const_lv32_22A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000101010";
    constant ap_const_lv32_22B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000101011";
    constant ap_const_lv32_24F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001001111";
    constant ap_const_lv32_250 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001010000";
    constant ap_const_lv32_274 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001110100";
    constant ap_const_lv32_275 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001110101";
    constant ap_const_lv32_299 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010011001";
    constant ap_const_lv37_0 : STD_LOGIC_VECTOR (36 downto 0) := "0000000000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_5B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011011";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_65 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100101";
    constant ap_const_lv32_79 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111001";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_89 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001001";
    constant ap_const_lv32_8A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001010";
    constant ap_const_lv32_9E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011110";
    constant ap_const_lv32_A5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100101";
    constant ap_const_lv32_AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101110";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_C3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000011";
    constant ap_const_lv32_CA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001010";
    constant ap_const_lv32_D3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010011";
    constant ap_const_lv32_D4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010100";
    constant ap_const_lv32_E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111000";
    constant ap_const_lv32_F9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111001";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_114 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010100";
    constant ap_const_lv32_11D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011101";
    constant ap_const_lv32_11E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011110";
    constant ap_const_lv32_132 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110010";
    constant ap_const_lv32_139 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111001";
    constant ap_const_lv32_142 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000010";
    constant ap_const_lv32_143 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000011";
    constant ap_const_lv32_157 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010111";
    constant ap_const_lv32_15E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011110";
    constant ap_const_lv32_167 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100111";
    constant ap_const_lv32_168 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101000";
    constant ap_const_lv32_17C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111100";
    constant ap_const_lv32_183 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000011";
    constant ap_const_lv32_18C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001100";
    constant ap_const_lv32_18D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001101";
    constant ap_const_lv32_1A1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100001";
    constant ap_const_lv32_1A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101000";
    constant ap_const_lv32_1B1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110001";
    constant ap_const_lv32_1B2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110010";
    constant ap_const_lv32_1C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000110";
    constant ap_const_lv32_1CD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001101";
    constant ap_const_lv32_1D6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010110";
    constant ap_const_lv32_1D7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010111";
    constant ap_const_lv32_1EB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101011";
    constant ap_const_lv32_1F2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110010";
    constant ap_const_lv32_1FB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111011";
    constant ap_const_lv32_1FC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111100";
    constant ap_const_lv32_210 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000010000";
    constant ap_const_lv32_217 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000010111";
    constant ap_const_lv32_220 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000100000";
    constant ap_const_lv32_221 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000100001";
    constant ap_const_lv32_235 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000110101";
    constant ap_const_lv32_23C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111100";
    constant ap_const_lv32_245 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001000101";
    constant ap_const_lv32_246 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001000110";
    constant ap_const_lv32_25A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001011010";
    constant ap_const_lv32_261 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001100001";
    constant ap_const_lv32_26A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001101010";
    constant ap_const_lv32_26B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001101011";
    constant ap_const_lv32_27F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001111111";
    constant ap_const_lv32_286 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010000110";
    constant ap_const_lv32_28F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010001111";
    constant ap_const_lv32_290 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010010000";
    constant ap_const_lv32_287 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010000111";
    constant ap_const_lv32_28E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010001110";
    constant ap_const_lv32_262 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001100010";
    constant ap_const_lv32_269 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001101001";
    constant ap_const_lv32_23D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111101";
    constant ap_const_lv32_244 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001000100";
    constant ap_const_lv32_218 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000011000";
    constant ap_const_lv32_21F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000011111";
    constant ap_const_lv32_1F3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110011";
    constant ap_const_lv32_1FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111010";
    constant ap_const_lv32_1CE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001110";
    constant ap_const_lv32_1D5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010101";
    constant ap_const_lv32_1A9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101001";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_184 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000100";
    constant ap_const_lv32_18B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001011";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_166 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100110";
    constant ap_const_lv32_13A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111010";
    constant ap_const_lv32_141 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000001";
    constant ap_const_lv32_115 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010101";
    constant ap_const_lv32_11C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011100";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110111";
    constant ap_const_lv32_CB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001011";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_A6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100110";
    constant ap_const_lv32_AD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101101";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_5C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011100";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_F9 : STD_LOGIC_VECTOR (7 downto 0) := "11111001";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln41_fu_1730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer7_out_blk_n : STD_LOGIC;
    signal layer8_out_blk_n : STD_LOGIC;
    signal i1_fu_332 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal i_fu_1724_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i1_load : STD_LOGIC_VECTOR (7 downto 0);
    signal layer7_out_read_local : STD_LOGIC;
    signal or_ln57_s_fu_1611_p55 : STD_LOGIC_VECTOR (323 downto 0);
    signal layer8_out_write_local : STD_LOGIC;
    signal trunc_ln44_fu_357_p1 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_fu_537_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_2_fu_547_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_1_fu_361_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_1_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_3_fu_579_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_5_fu_589_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_2_fu_371_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_2_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_6_fu_621_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_8_fu_631_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_3_fu_381_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_3_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_9_fu_663_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_s_fu_673_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_4_fu_391_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_4_fu_699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_1_fu_705_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_4_fu_715_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_5_fu_401_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_5_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_7_fu_747_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_10_fu_757_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_6_fu_411_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_6_fu_783_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_11_fu_789_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_12_fu_799_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_7_fu_421_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_7_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_13_fu_831_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_14_fu_841_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_8_fu_431_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_8_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_15_fu_873_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_16_fu_883_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_9_fu_441_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_9_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_17_fu_915_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_18_fu_925_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_s_fu_451_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_10_fu_951_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_19_fu_957_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_20_fu_967_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_10_fu_461_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_11_fu_993_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_21_fu_999_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_22_fu_1009_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_11_fu_471_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_12_fu_1035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_23_fu_1041_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_24_fu_1051_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_12_fu_481_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_13_fu_1077_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_25_fu_1083_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_26_fu_1093_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_13_fu_491_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_14_fu_1119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_27_fu_1125_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_28_fu_1135_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_14_fu_501_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_15_fu_1161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_29_fu_1167_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_30_fu_1177_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_15_fu_511_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_16_fu_1203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_31_fu_1209_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_32_fu_1219_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln44_16_fu_521_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal icmp_ln51_17_fu_1245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_33_fu_1251_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_34_fu_1261_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_1287_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_1305_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_1323_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_1341_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_1359_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_1377_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_1395_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_1413_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_1431_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_1449_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_1467_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_1485_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_1503_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_1521_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_1539_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_1557_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_1575_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_fu_1593_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge_fu_1279_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_63_fu_1297_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_53194_0_0_fu_1271_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_62_fu_1237_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_64_fu_1315_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_50190_0_0_fu_1229_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_61_fu_1195_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_65_fu_1333_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_47186_0_0_fu_1187_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_60_fu_1153_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_66_fu_1351_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_44182_0_0_fu_1145_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_59_fu_1111_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_67_fu_1369_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_41178_0_0_fu_1103_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_58_fu_1069_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_68_fu_1387_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_38174_0_0_fu_1061_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_57_fu_1027_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_69_fu_1405_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_35170_0_0_fu_1019_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_56_fu_985_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_70_fu_1423_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_32166_0_0_fu_977_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_55_fu_943_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_71_fu_1441_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_29162_0_0_fu_935_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_54_fu_901_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_72_fu_1459_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_26158_0_0_fu_893_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_53_fu_859_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_73_fu_1477_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_23154_0_0_fu_851_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_52_fu_817_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_74_fu_1495_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_20150_0_0_fu_809_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_51_fu_775_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_75_fu_1513_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_17146_0_0_fu_767_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_50_fu_733_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_76_fu_1531_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_14142_0_0_fu_725_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_49_fu_691_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_77_fu_1549_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_11138_0_0_fu_683_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_48_fu_649_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_78_fu_1567_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_8134_0_0_fu_641_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_47_fu_607_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_79_fu_1585_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_5130_0_0_fu_599_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_565_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_80_fu_1603_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_data_sroa_0_0_0_fu_557_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_fu_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                i1_fu_332 <= i_fu_1724_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(layer7_out_empty_n, layer8_out_full_n, ap_done_reg, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (layer8_out_full_n = ap_const_logic_0) or (layer7_out_empty_n = ap_const_logic_0) or (ap_start_int = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln41_fu_1730_p2)
    begin
        if (((icmp_ln41_fu_1730_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i1_load_assign_proc : process(ap_CS_fsm_state1, i1_fu_332, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i1_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i1_load <= i1_fu_332;
        end if; 
    end process;

    empty_47_fu_607_p3 <= 
        trunc_ln52_5_fu_589_p4 when (icmp_ln51_1_fu_573_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_48_fu_649_p3 <= 
        trunc_ln52_8_fu_631_p4 when (icmp_ln51_2_fu_615_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_49_fu_691_p3 <= 
        trunc_ln52_s_fu_673_p4 when (icmp_ln51_3_fu_657_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_50_fu_733_p3 <= 
        trunc_ln52_4_fu_715_p4 when (icmp_ln51_4_fu_699_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_51_fu_775_p3 <= 
        trunc_ln52_10_fu_757_p4 when (icmp_ln51_5_fu_741_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_52_fu_817_p3 <= 
        trunc_ln52_12_fu_799_p4 when (icmp_ln51_6_fu_783_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_53_fu_859_p3 <= 
        trunc_ln52_14_fu_841_p4 when (icmp_ln51_7_fu_825_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_54_fu_901_p3 <= 
        trunc_ln52_16_fu_883_p4 when (icmp_ln51_8_fu_867_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_55_fu_943_p3 <= 
        trunc_ln52_18_fu_925_p4 when (icmp_ln51_9_fu_909_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_56_fu_985_p3 <= 
        trunc_ln52_20_fu_967_p4 when (icmp_ln51_10_fu_951_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_57_fu_1027_p3 <= 
        trunc_ln52_22_fu_1009_p4 when (icmp_ln51_11_fu_993_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_58_fu_1069_p3 <= 
        trunc_ln52_24_fu_1051_p4 when (icmp_ln51_12_fu_1035_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_59_fu_1111_p3 <= 
        trunc_ln52_26_fu_1093_p4 when (icmp_ln51_13_fu_1077_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_60_fu_1153_p3 <= 
        trunc_ln52_28_fu_1135_p4 when (icmp_ln51_14_fu_1119_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_61_fu_1195_p3 <= 
        trunc_ln52_30_fu_1177_p4 when (icmp_ln51_15_fu_1161_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_62_fu_1237_p3 <= 
        trunc_ln52_32_fu_1219_p4 when (icmp_ln51_16_fu_1203_p2(0) = '1') else 
        ap_const_lv2_0;
    empty_63_fu_1297_p3 <= 
        tmp_fu_1287_p4 when (icmp_ln51_17_fu_1245_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_64_fu_1315_p3 <= 
        tmp_1_fu_1305_p4 when (icmp_ln51_16_fu_1203_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_65_fu_1333_p3 <= 
        tmp_2_fu_1323_p4 when (icmp_ln51_15_fu_1161_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_66_fu_1351_p3 <= 
        tmp_3_fu_1341_p4 when (icmp_ln51_14_fu_1119_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_67_fu_1369_p3 <= 
        tmp_4_fu_1359_p4 when (icmp_ln51_13_fu_1077_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_68_fu_1387_p3 <= 
        tmp_5_fu_1377_p4 when (icmp_ln51_12_fu_1035_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_69_fu_1405_p3 <= 
        tmp_6_fu_1395_p4 when (icmp_ln51_11_fu_993_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_70_fu_1423_p3 <= 
        tmp_7_fu_1413_p4 when (icmp_ln51_10_fu_951_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_71_fu_1441_p3 <= 
        tmp_8_fu_1431_p4 when (icmp_ln51_9_fu_909_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_72_fu_1459_p3 <= 
        tmp_9_fu_1449_p4 when (icmp_ln51_8_fu_867_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_73_fu_1477_p3 <= 
        tmp_s_fu_1467_p4 when (icmp_ln51_7_fu_825_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_74_fu_1495_p3 <= 
        tmp_10_fu_1485_p4 when (icmp_ln51_6_fu_783_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_75_fu_1513_p3 <= 
        tmp_11_fu_1503_p4 when (icmp_ln51_5_fu_741_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_76_fu_1531_p3 <= 
        tmp_12_fu_1521_p4 when (icmp_ln51_4_fu_699_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_77_fu_1549_p3 <= 
        tmp_13_fu_1539_p4 when (icmp_ln51_3_fu_657_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_78_fu_1567_p3 <= 
        tmp_14_fu_1557_p4 when (icmp_ln51_2_fu_615_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_79_fu_1585_p3 <= 
        tmp_15_fu_1575_p4 when (icmp_ln51_1_fu_573_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_80_fu_1603_p3 <= 
        tmp_16_fu_1593_p4 when (icmp_ln51_fu_531_p2(0) = '1') else 
        ap_const_lv8_0;
    empty_fu_565_p3 <= 
        trunc_ln52_2_fu_547_p4 when (icmp_ln51_fu_531_p2(0) = '1') else 
        ap_const_lv2_0;
    i_fu_1724_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i1_load) + unsigned(ap_const_lv8_1));
    icmp_ln41_fu_1730_p2 <= "1" when (ap_sig_allocacmp_i1_load = ap_const_lv8_F9) else "0";
    icmp_ln51_10_fu_951_p2 <= "1" when (signed(trunc_ln44_s_fu_451_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_11_fu_993_p2 <= "1" when (signed(trunc_ln44_10_fu_461_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_12_fu_1035_p2 <= "1" when (signed(trunc_ln44_11_fu_471_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_13_fu_1077_p2 <= "1" when (signed(trunc_ln44_12_fu_481_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_14_fu_1119_p2 <= "1" when (signed(trunc_ln44_13_fu_491_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_15_fu_1161_p2 <= "1" when (signed(trunc_ln44_14_fu_501_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_16_fu_1203_p2 <= "1" when (signed(trunc_ln44_15_fu_511_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_17_fu_1245_p2 <= "1" when (signed(trunc_ln44_16_fu_521_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_1_fu_573_p2 <= "1" when (signed(trunc_ln44_1_fu_361_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_2_fu_615_p2 <= "1" when (signed(trunc_ln44_2_fu_371_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_3_fu_657_p2 <= "1" when (signed(trunc_ln44_3_fu_381_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_4_fu_699_p2 <= "1" when (signed(trunc_ln44_4_fu_391_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_5_fu_741_p2 <= "1" when (signed(trunc_ln44_5_fu_401_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_6_fu_783_p2 <= "1" when (signed(trunc_ln44_6_fu_411_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_7_fu_825_p2 <= "1" when (signed(trunc_ln44_7_fu_421_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_8_fu_867_p2 <= "1" when (signed(trunc_ln44_8_fu_431_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_9_fu_909_p2 <= "1" when (signed(trunc_ln44_9_fu_441_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_fu_531_p2 <= "1" when (signed(trunc_ln44_fu_357_p1) > signed(ap_const_lv37_0)) else "0";

    layer7_out_blk_n_assign_proc : process(ap_CS_fsm_state1, layer7_out_empty_n, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer7_out_blk_n <= layer7_out_empty_n;
        else 
            layer7_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer7_out_read <= layer7_out_read_local;

    layer7_out_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer7_out_read_local <= ap_const_logic_1;
        else 
            layer7_out_read_local <= ap_const_logic_0;
        end if; 
    end process;


    layer8_out_blk_n_assign_proc : process(ap_CS_fsm_state1, layer8_out_full_n, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer8_out_blk_n <= layer8_out_full_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer8_out_din <= or_ln57_s_fu_1611_p55;
    layer8_out_write <= layer8_out_write_local;

    layer8_out_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer8_out_write_local <= ap_const_logic_1;
        else 
            layer8_out_write_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_1611_p55 <= (((((((((((((((((((((((((((((((((((((((((((((((((((((storemerge_fu_1279_p3 & empty_63_fu_1297_p3) & out_data_sroa_53194_0_0_fu_1271_p3) & empty_62_fu_1237_p3) & empty_64_fu_1315_p3) & out_data_sroa_50190_0_0_fu_1229_p3) & empty_61_fu_1195_p3) & empty_65_fu_1333_p3) & out_data_sroa_47186_0_0_fu_1187_p3) & empty_60_fu_1153_p3) & empty_66_fu_1351_p3) & out_data_sroa_44182_0_0_fu_1145_p3) & empty_59_fu_1111_p3) & empty_67_fu_1369_p3) & out_data_sroa_41178_0_0_fu_1103_p3) & empty_58_fu_1069_p3) & empty_68_fu_1387_p3) & out_data_sroa_38174_0_0_fu_1061_p3) & empty_57_fu_1027_p3) & empty_69_fu_1405_p3) & out_data_sroa_35170_0_0_fu_1019_p3) & empty_56_fu_985_p3) & empty_70_fu_1423_p3) & out_data_sroa_32166_0_0_fu_977_p3) & empty_55_fu_943_p3) & empty_71_fu_1441_p3) & out_data_sroa_29162_0_0_fu_935_p3) & empty_54_fu_901_p3) & empty_72_fu_1459_p3) & out_data_sroa_26158_0_0_fu_893_p3) & empty_53_fu_859_p3) & empty_73_fu_1477_p3) & out_data_sroa_23154_0_0_fu_851_p3) & empty_52_fu_817_p3) & empty_74_fu_1495_p3) & out_data_sroa_20150_0_0_fu_809_p3) 
    & empty_51_fu_775_p3) & empty_75_fu_1513_p3) & out_data_sroa_17146_0_0_fu_767_p3) & empty_50_fu_733_p3) & empty_76_fu_1531_p3) & out_data_sroa_14142_0_0_fu_725_p3) & empty_49_fu_691_p3) & empty_77_fu_1549_p3) & out_data_sroa_11138_0_0_fu_683_p3) & empty_48_fu_649_p3) & empty_78_fu_1567_p3) & out_data_sroa_8134_0_0_fu_641_p3) & empty_47_fu_607_p3) & empty_79_fu_1585_p3) & out_data_sroa_5130_0_0_fu_599_p3) & empty_fu_565_p3) & empty_80_fu_1603_p3) & out_data_sroa_0_0_0_fu_557_p3);
    out_data_sroa_0_0_0_fu_557_p3 <= 
        trunc_ln1_fu_537_p4 when (icmp_ln51_fu_531_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_11138_0_0_fu_683_p3 <= 
        trunc_ln52_9_fu_663_p4 when (icmp_ln51_3_fu_657_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_14142_0_0_fu_725_p3 <= 
        trunc_ln52_1_fu_705_p4 when (icmp_ln51_4_fu_699_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_17146_0_0_fu_767_p3 <= 
        trunc_ln52_7_fu_747_p4 when (icmp_ln51_5_fu_741_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_20150_0_0_fu_809_p3 <= 
        trunc_ln52_11_fu_789_p4 when (icmp_ln51_6_fu_783_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_23154_0_0_fu_851_p3 <= 
        trunc_ln52_13_fu_831_p4 when (icmp_ln51_7_fu_825_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_26158_0_0_fu_893_p3 <= 
        trunc_ln52_15_fu_873_p4 when (icmp_ln51_8_fu_867_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_29162_0_0_fu_935_p3 <= 
        trunc_ln52_17_fu_915_p4 when (icmp_ln51_9_fu_909_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_32166_0_0_fu_977_p3 <= 
        trunc_ln52_19_fu_957_p4 when (icmp_ln51_10_fu_951_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_35170_0_0_fu_1019_p3 <= 
        trunc_ln52_21_fu_999_p4 when (icmp_ln51_11_fu_993_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_38174_0_0_fu_1061_p3 <= 
        trunc_ln52_23_fu_1041_p4 when (icmp_ln51_12_fu_1035_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_41178_0_0_fu_1103_p3 <= 
        trunc_ln52_25_fu_1083_p4 when (icmp_ln51_13_fu_1077_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_44182_0_0_fu_1145_p3 <= 
        trunc_ln52_27_fu_1125_p4 when (icmp_ln51_14_fu_1119_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_47186_0_0_fu_1187_p3 <= 
        trunc_ln52_29_fu_1167_p4 when (icmp_ln51_15_fu_1161_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_50190_0_0_fu_1229_p3 <= 
        trunc_ln52_31_fu_1209_p4 when (icmp_ln51_16_fu_1203_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_5130_0_0_fu_599_p3 <= 
        trunc_ln52_3_fu_579_p4 when (icmp_ln51_1_fu_573_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_53194_0_0_fu_1271_p3 <= 
        trunc_ln52_33_fu_1251_p4 when (icmp_ln51_17_fu_1245_p2(0) = '1') else 
        ap_const_lv8_0;
    out_data_sroa_8134_0_0_fu_641_p3 <= 
        trunc_ln52_6_fu_621_p4 when (icmp_ln51_2_fu_615_p2(0) = '1') else 
        ap_const_lv8_0;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    storemerge_fu_1279_p3 <= 
        trunc_ln52_34_fu_1261_p4 when (icmp_ln51_17_fu_1245_p2(0) = '1') else 
        ap_const_lv2_0;
    tmp_10_fu_1485_p4 <= layer7_out_dout(247 downto 240);
    tmp_11_fu_1503_p4 <= layer7_out_dout(210 downto 203);
    tmp_12_fu_1521_p4 <= layer7_out_dout(173 downto 166);
    tmp_13_fu_1539_p4 <= layer7_out_dout(136 downto 129);
    tmp_14_fu_1557_p4 <= layer7_out_dout(99 downto 92);
    tmp_15_fu_1575_p4 <= layer7_out_dout(62 downto 55);
    tmp_16_fu_1593_p4 <= layer7_out_dout(25 downto 18);
    tmp_1_fu_1305_p4 <= layer7_out_dout(617 downto 610);
    tmp_2_fu_1323_p4 <= layer7_out_dout(580 downto 573);
    tmp_3_fu_1341_p4 <= layer7_out_dout(543 downto 536);
    tmp_4_fu_1359_p4 <= layer7_out_dout(506 downto 499);
    tmp_5_fu_1377_p4 <= layer7_out_dout(469 downto 462);
    tmp_6_fu_1395_p4 <= layer7_out_dout(432 downto 425);
    tmp_7_fu_1413_p4 <= layer7_out_dout(395 downto 388);
    tmp_8_fu_1431_p4 <= layer7_out_dout(358 downto 351);
    tmp_9_fu_1449_p4 <= layer7_out_dout(321 downto 314);
    tmp_fu_1287_p4 <= layer7_out_dout(654 downto 647);
    tmp_s_fu_1467_p4 <= layer7_out_dout(284 downto 277);
    trunc_ln1_fu_537_p4 <= layer7_out_dout(17 downto 10);
    trunc_ln44_10_fu_461_p4 <= layer7_out_dout(443 downto 407);
    trunc_ln44_11_fu_471_p4 <= layer7_out_dout(480 downto 444);
    trunc_ln44_12_fu_481_p4 <= layer7_out_dout(517 downto 481);
    trunc_ln44_13_fu_491_p4 <= layer7_out_dout(554 downto 518);
    trunc_ln44_14_fu_501_p4 <= layer7_out_dout(591 downto 555);
    trunc_ln44_15_fu_511_p4 <= layer7_out_dout(628 downto 592);
    trunc_ln44_16_fu_521_p4 <= layer7_out_dout(665 downto 629);
    trunc_ln44_1_fu_361_p4 <= layer7_out_dout(73 downto 37);
    trunc_ln44_2_fu_371_p4 <= layer7_out_dout(110 downto 74);
    trunc_ln44_3_fu_381_p4 <= layer7_out_dout(147 downto 111);
    trunc_ln44_4_fu_391_p4 <= layer7_out_dout(184 downto 148);
    trunc_ln44_5_fu_401_p4 <= layer7_out_dout(221 downto 185);
    trunc_ln44_6_fu_411_p4 <= layer7_out_dout(258 downto 222);
    trunc_ln44_7_fu_421_p4 <= layer7_out_dout(295 downto 259);
    trunc_ln44_8_fu_431_p4 <= layer7_out_dout(332 downto 296);
    trunc_ln44_9_fu_441_p4 <= layer7_out_dout(369 downto 333);
    trunc_ln44_fu_357_p1 <= layer7_out_dout(37 - 1 downto 0);
    trunc_ln44_s_fu_451_p4 <= layer7_out_dout(406 downto 370);
    trunc_ln52_10_fu_757_p4 <= layer7_out_dout(212 downto 211);
    trunc_ln52_11_fu_789_p4 <= layer7_out_dout(239 downto 232);
    trunc_ln52_12_fu_799_p4 <= layer7_out_dout(249 downto 248);
    trunc_ln52_13_fu_831_p4 <= layer7_out_dout(276 downto 269);
    trunc_ln52_14_fu_841_p4 <= layer7_out_dout(286 downto 285);
    trunc_ln52_15_fu_873_p4 <= layer7_out_dout(313 downto 306);
    trunc_ln52_16_fu_883_p4 <= layer7_out_dout(323 downto 322);
    trunc_ln52_17_fu_915_p4 <= layer7_out_dout(350 downto 343);
    trunc_ln52_18_fu_925_p4 <= layer7_out_dout(360 downto 359);
    trunc_ln52_19_fu_957_p4 <= layer7_out_dout(387 downto 380);
    trunc_ln52_1_fu_705_p4 <= layer7_out_dout(165 downto 158);
    trunc_ln52_20_fu_967_p4 <= layer7_out_dout(397 downto 396);
    trunc_ln52_21_fu_999_p4 <= layer7_out_dout(424 downto 417);
    trunc_ln52_22_fu_1009_p4 <= layer7_out_dout(434 downto 433);
    trunc_ln52_23_fu_1041_p4 <= layer7_out_dout(461 downto 454);
    trunc_ln52_24_fu_1051_p4 <= layer7_out_dout(471 downto 470);
    trunc_ln52_25_fu_1083_p4 <= layer7_out_dout(498 downto 491);
    trunc_ln52_26_fu_1093_p4 <= layer7_out_dout(508 downto 507);
    trunc_ln52_27_fu_1125_p4 <= layer7_out_dout(535 downto 528);
    trunc_ln52_28_fu_1135_p4 <= layer7_out_dout(545 downto 544);
    trunc_ln52_29_fu_1167_p4 <= layer7_out_dout(572 downto 565);
    trunc_ln52_2_fu_547_p4 <= layer7_out_dout(27 downto 26);
    trunc_ln52_30_fu_1177_p4 <= layer7_out_dout(582 downto 581);
    trunc_ln52_31_fu_1209_p4 <= layer7_out_dout(609 downto 602);
    trunc_ln52_32_fu_1219_p4 <= layer7_out_dout(619 downto 618);
    trunc_ln52_33_fu_1251_p4 <= layer7_out_dout(646 downto 639);
    trunc_ln52_34_fu_1261_p4 <= layer7_out_dout(656 downto 655);
    trunc_ln52_3_fu_579_p4 <= layer7_out_dout(54 downto 47);
    trunc_ln52_4_fu_715_p4 <= layer7_out_dout(175 downto 174);
    trunc_ln52_5_fu_589_p4 <= layer7_out_dout(64 downto 63);
    trunc_ln52_6_fu_621_p4 <= layer7_out_dout(91 downto 84);
    trunc_ln52_7_fu_747_p4 <= layer7_out_dout(202 downto 195);
    trunc_ln52_8_fu_631_p4 <= layer7_out_dout(101 downto 100);
    trunc_ln52_9_fu_663_p4 <= layer7_out_dout(128 downto 121);
    trunc_ln52_s_fu_673_p4 <= layer7_out_dout(138 downto 137);
end behav;
