// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_12u_array_ap_fixed_18_8_5_3_0_12u_relu_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer3_out_dout,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer3_out_empty_n,
        layer3_out_read,
        layer4_out_din,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_full_n,
        layer4_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [443:0] layer3_out_dout;
input  [10:0] layer3_out_num_data_valid;
input  [10:0] layer3_out_fifo_cap;
input   layer3_out_empty_n;
output   layer3_out_read;
output  [215:0] layer4_out_din;
input  [10:0] layer4_out_num_data_valid;
input  [10:0] layer4_out_fifo_cap;
input   layer4_out_full_n;
output   layer4_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln41_fu_1180_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer3_out_blk_n;
reg    layer4_out_blk_n;
reg   [9:0] i1_fu_238;
wire   [9:0] i_fu_1174_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i1_load;
reg    layer3_out_read_local;
wire   [215:0] or_ln57_s_fu_1097_p37;
reg    layer4_out_write_local;
wire   [36:0] trunc_ln44_fu_263_p1;
wire   [0:0] icmp_ln51_fu_377_p2;
wire   [7:0] trunc_ln2_fu_383_p4;
wire   [1:0] trunc_ln52_s_fu_393_p4;
wire   [36:0] trunc_ln44_s_fu_267_p4;
wire   [0:0] icmp_ln51_18_fu_419_p2;
wire   [7:0] trunc_ln52_35_fu_425_p4;
wire   [1:0] trunc_ln52_36_fu_435_p4;
wire   [36:0] trunc_ln44_17_fu_277_p4;
wire   [0:0] icmp_ln51_19_fu_461_p2;
wire   [7:0] trunc_ln52_37_fu_467_p4;
wire   [1:0] trunc_ln52_38_fu_477_p4;
wire   [36:0] trunc_ln44_18_fu_287_p4;
wire   [0:0] icmp_ln51_20_fu_503_p2;
wire   [7:0] trunc_ln52_39_fu_509_p4;
wire   [1:0] trunc_ln52_40_fu_519_p4;
wire   [36:0] trunc_ln44_19_fu_297_p4;
wire   [0:0] icmp_ln51_21_fu_545_p2;
wire   [7:0] trunc_ln52_41_fu_551_p4;
wire   [1:0] trunc_ln52_42_fu_561_p4;
wire   [36:0] trunc_ln44_20_fu_307_p4;
wire   [0:0] icmp_ln51_22_fu_587_p2;
wire   [7:0] trunc_ln52_43_fu_593_p4;
wire   [1:0] trunc_ln52_44_fu_603_p4;
wire   [36:0] trunc_ln44_21_fu_317_p4;
wire   [0:0] icmp_ln51_23_fu_629_p2;
wire   [7:0] trunc_ln52_45_fu_635_p4;
wire   [1:0] trunc_ln52_46_fu_645_p4;
wire   [36:0] trunc_ln44_22_fu_327_p4;
wire   [0:0] icmp_ln51_24_fu_671_p2;
wire   [7:0] trunc_ln52_47_fu_677_p4;
wire   [1:0] trunc_ln52_48_fu_687_p4;
wire   [36:0] trunc_ln44_23_fu_337_p4;
wire   [0:0] icmp_ln51_25_fu_713_p2;
wire   [7:0] trunc_ln52_49_fu_719_p4;
wire   [1:0] trunc_ln52_50_fu_729_p4;
wire   [36:0] trunc_ln44_24_fu_347_p4;
wire   [0:0] icmp_ln51_26_fu_755_p2;
wire   [7:0] trunc_ln52_51_fu_761_p4;
wire   [1:0] trunc_ln52_52_fu_771_p4;
wire   [36:0] trunc_ln44_25_fu_357_p4;
wire   [0:0] icmp_ln51_27_fu_797_p2;
wire   [7:0] trunc_ln52_53_fu_803_p4;
wire   [1:0] trunc_ln52_54_fu_813_p4;
wire   [36:0] trunc_ln44_26_fu_367_p4;
wire   [0:0] icmp_ln51_28_fu_839_p2;
wire   [7:0] trunc_ln52_55_fu_845_p4;
wire   [1:0] trunc_ln52_56_fu_855_p4;
wire   [7:0] tmp_fu_881_p4;
wire   [7:0] tmp_s_fu_899_p4;
wire   [7:0] tmp_17_fu_917_p4;
wire   [7:0] tmp_18_fu_935_p4;
wire   [7:0] tmp_19_fu_953_p4;
wire   [7:0] tmp_20_fu_971_p4;
wire   [7:0] tmp_21_fu_989_p4;
wire   [7:0] tmp_22_fu_1007_p4;
wire   [7:0] tmp_23_fu_1025_p4;
wire   [7:0] tmp_24_fu_1043_p4;
wire   [7:0] tmp_25_fu_1061_p4;
wire   [7:0] tmp_26_fu_1079_p4;
wire   [1:0] storemerge_fu_873_p3;
wire   [7:0] empty_91_fu_891_p3;
wire   [7:0] out_data_sroa_35140_0_0_fu_865_p3;
wire   [1:0] empty_90_fu_831_p3;
wire   [7:0] empty_92_fu_909_p3;
wire   [7:0] out_data_sroa_32136_0_0_fu_823_p3;
wire   [1:0] empty_89_fu_789_p3;
wire   [7:0] empty_93_fu_927_p3;
wire   [7:0] out_data_sroa_29132_0_0_fu_781_p3;
wire   [1:0] empty_88_fu_747_p3;
wire   [7:0] empty_94_fu_945_p3;
wire   [7:0] out_data_sroa_26128_0_0_fu_739_p3;
wire   [1:0] empty_87_fu_705_p3;
wire   [7:0] empty_95_fu_963_p3;
wire   [7:0] out_data_sroa_23124_0_0_fu_697_p3;
wire   [1:0] empty_86_fu_663_p3;
wire   [7:0] empty_96_fu_981_p3;
wire   [7:0] out_data_sroa_20120_0_0_fu_655_p3;
wire   [1:0] empty_85_fu_621_p3;
wire   [7:0] empty_97_fu_999_p3;
wire   [7:0] out_data_sroa_17116_0_0_fu_613_p3;
wire   [1:0] empty_84_fu_579_p3;
wire   [7:0] empty_98_fu_1017_p3;
wire   [7:0] out_data_sroa_14112_0_0_fu_571_p3;
wire   [1:0] empty_83_fu_537_p3;
wire   [7:0] empty_99_fu_1035_p3;
wire   [7:0] out_data_sroa_11108_0_0_fu_529_p3;
wire   [1:0] empty_82_fu_495_p3;
wire   [7:0] empty_100_fu_1053_p3;
wire   [7:0] out_data_sroa_8104_0_0_fu_487_p3;
wire   [1:0] empty_81_fu_453_p3;
wire   [7:0] empty_101_fu_1071_p3;
wire   [7:0] out_data_sroa_5100_0_0_fu_445_p3;
wire   [1:0] empty_fu_411_p3;
wire   [7:0] empty_102_fu_1089_p3;
wire   [7:0] out_data_sroa_0_0_0_fu_403_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 i1_fu_238 = 10'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i1_fu_238 <= i_fu_1174_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_1180_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i1_load = 10'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_238;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_read_local = 1'b1;
    end else begin
        layer3_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_write_local = 1'b1;
    end else begin
        layer4_out_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (ap_done_reg == 1'b1) | (layer4_out_full_n == 1'b0) | (layer3_out_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign empty_100_fu_1053_p3 = ((icmp_ln51_19_fu_461_p2[0:0] == 1'b1) ? tmp_24_fu_1043_p4 : 8'd0);

assign empty_101_fu_1071_p3 = ((icmp_ln51_18_fu_419_p2[0:0] == 1'b1) ? tmp_25_fu_1061_p4 : 8'd0);

assign empty_102_fu_1089_p3 = ((icmp_ln51_fu_377_p2[0:0] == 1'b1) ? tmp_26_fu_1079_p4 : 8'd0);

assign empty_81_fu_453_p3 = ((icmp_ln51_18_fu_419_p2[0:0] == 1'b1) ? trunc_ln52_36_fu_435_p4 : 2'd0);

assign empty_82_fu_495_p3 = ((icmp_ln51_19_fu_461_p2[0:0] == 1'b1) ? trunc_ln52_38_fu_477_p4 : 2'd0);

assign empty_83_fu_537_p3 = ((icmp_ln51_20_fu_503_p2[0:0] == 1'b1) ? trunc_ln52_40_fu_519_p4 : 2'd0);

assign empty_84_fu_579_p3 = ((icmp_ln51_21_fu_545_p2[0:0] == 1'b1) ? trunc_ln52_42_fu_561_p4 : 2'd0);

assign empty_85_fu_621_p3 = ((icmp_ln51_22_fu_587_p2[0:0] == 1'b1) ? trunc_ln52_44_fu_603_p4 : 2'd0);

assign empty_86_fu_663_p3 = ((icmp_ln51_23_fu_629_p2[0:0] == 1'b1) ? trunc_ln52_46_fu_645_p4 : 2'd0);

assign empty_87_fu_705_p3 = ((icmp_ln51_24_fu_671_p2[0:0] == 1'b1) ? trunc_ln52_48_fu_687_p4 : 2'd0);

assign empty_88_fu_747_p3 = ((icmp_ln51_25_fu_713_p2[0:0] == 1'b1) ? trunc_ln52_50_fu_729_p4 : 2'd0);

assign empty_89_fu_789_p3 = ((icmp_ln51_26_fu_755_p2[0:0] == 1'b1) ? trunc_ln52_52_fu_771_p4 : 2'd0);

assign empty_90_fu_831_p3 = ((icmp_ln51_27_fu_797_p2[0:0] == 1'b1) ? trunc_ln52_54_fu_813_p4 : 2'd0);

assign empty_91_fu_891_p3 = ((icmp_ln51_28_fu_839_p2[0:0] == 1'b1) ? tmp_fu_881_p4 : 8'd0);

assign empty_92_fu_909_p3 = ((icmp_ln51_27_fu_797_p2[0:0] == 1'b1) ? tmp_s_fu_899_p4 : 8'd0);

assign empty_93_fu_927_p3 = ((icmp_ln51_26_fu_755_p2[0:0] == 1'b1) ? tmp_17_fu_917_p4 : 8'd0);

assign empty_94_fu_945_p3 = ((icmp_ln51_25_fu_713_p2[0:0] == 1'b1) ? tmp_18_fu_935_p4 : 8'd0);

assign empty_95_fu_963_p3 = ((icmp_ln51_24_fu_671_p2[0:0] == 1'b1) ? tmp_19_fu_953_p4 : 8'd0);

assign empty_96_fu_981_p3 = ((icmp_ln51_23_fu_629_p2[0:0] == 1'b1) ? tmp_20_fu_971_p4 : 8'd0);

assign empty_97_fu_999_p3 = ((icmp_ln51_22_fu_587_p2[0:0] == 1'b1) ? tmp_21_fu_989_p4 : 8'd0);

assign empty_98_fu_1017_p3 = ((icmp_ln51_21_fu_545_p2[0:0] == 1'b1) ? tmp_22_fu_1007_p4 : 8'd0);

assign empty_99_fu_1035_p3 = ((icmp_ln51_20_fu_503_p2[0:0] == 1'b1) ? tmp_23_fu_1025_p4 : 8'd0);

assign empty_fu_411_p3 = ((icmp_ln51_fu_377_p2[0:0] == 1'b1) ? trunc_ln52_s_fu_393_p4 : 2'd0);

assign i_fu_1174_p2 = (ap_sig_allocacmp_i1_load + 10'd1);

assign icmp_ln41_fu_1180_p2 = ((ap_sig_allocacmp_i1_load == 10'd1019) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_419_p2 = (($signed(trunc_ln44_s_fu_267_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_461_p2 = (($signed(trunc_ln44_17_fu_277_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_503_p2 = (($signed(trunc_ln44_18_fu_287_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_545_p2 = (($signed(trunc_ln44_19_fu_297_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_587_p2 = (($signed(trunc_ln44_20_fu_307_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_629_p2 = (($signed(trunc_ln44_21_fu_317_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_671_p2 = (($signed(trunc_ln44_22_fu_327_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_713_p2 = (($signed(trunc_ln44_23_fu_337_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_755_p2 = (($signed(trunc_ln44_24_fu_347_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_797_p2 = (($signed(trunc_ln44_25_fu_357_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_839_p2 = (($signed(trunc_ln44_26_fu_367_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_377_p2 = (($signed(trunc_ln44_fu_263_p1) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign layer3_out_read = layer3_out_read_local;

assign layer4_out_din = or_ln57_s_fu_1097_p37;

assign layer4_out_write = layer4_out_write_local;

assign or_ln57_s_fu_1097_p37 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{storemerge_fu_873_p3}, {empty_91_fu_891_p3}}, {out_data_sroa_35140_0_0_fu_865_p3}}, {empty_90_fu_831_p3}}, {empty_92_fu_909_p3}}, {out_data_sroa_32136_0_0_fu_823_p3}}, {empty_89_fu_789_p3}}, {empty_93_fu_927_p3}}, {out_data_sroa_29132_0_0_fu_781_p3}}, {empty_88_fu_747_p3}}, {empty_94_fu_945_p3}}, {out_data_sroa_26128_0_0_fu_739_p3}}, {empty_87_fu_705_p3}}, {empty_95_fu_963_p3}}, {out_data_sroa_23124_0_0_fu_697_p3}}, {empty_86_fu_663_p3}}, {empty_96_fu_981_p3}}, {out_data_sroa_20120_0_0_fu_655_p3}}, {empty_85_fu_621_p3}}, {empty_97_fu_999_p3}}, {out_data_sroa_17116_0_0_fu_613_p3}}, {empty_84_fu_579_p3}}, {empty_98_fu_1017_p3}}, {out_data_sroa_14112_0_0_fu_571_p3}}, {empty_83_fu_537_p3}}, {empty_99_fu_1035_p3}}, {out_data_sroa_11108_0_0_fu_529_p3}}, {empty_82_fu_495_p3}}, {empty_100_fu_1053_p3}}, {out_data_sroa_8104_0_0_fu_487_p3}}, {empty_81_fu_453_p3}}, {empty_101_fu_1071_p3}}, {out_data_sroa_5100_0_0_fu_445_p3}}, {empty_fu_411_p3}}, {empty_102_fu_1089_p3}}, {out_data_sroa_0_0_0_fu_403_p3}};

assign out_data_sroa_0_0_0_fu_403_p3 = ((icmp_ln51_fu_377_p2[0:0] == 1'b1) ? trunc_ln2_fu_383_p4 : 8'd0);

assign out_data_sroa_11108_0_0_fu_529_p3 = ((icmp_ln51_20_fu_503_p2[0:0] == 1'b1) ? trunc_ln52_39_fu_509_p4 : 8'd0);

assign out_data_sroa_14112_0_0_fu_571_p3 = ((icmp_ln51_21_fu_545_p2[0:0] == 1'b1) ? trunc_ln52_41_fu_551_p4 : 8'd0);

assign out_data_sroa_17116_0_0_fu_613_p3 = ((icmp_ln51_22_fu_587_p2[0:0] == 1'b1) ? trunc_ln52_43_fu_593_p4 : 8'd0);

assign out_data_sroa_20120_0_0_fu_655_p3 = ((icmp_ln51_23_fu_629_p2[0:0] == 1'b1) ? trunc_ln52_45_fu_635_p4 : 8'd0);

assign out_data_sroa_23124_0_0_fu_697_p3 = ((icmp_ln51_24_fu_671_p2[0:0] == 1'b1) ? trunc_ln52_47_fu_677_p4 : 8'd0);

assign out_data_sroa_26128_0_0_fu_739_p3 = ((icmp_ln51_25_fu_713_p2[0:0] == 1'b1) ? trunc_ln52_49_fu_719_p4 : 8'd0);

assign out_data_sroa_29132_0_0_fu_781_p3 = ((icmp_ln51_26_fu_755_p2[0:0] == 1'b1) ? trunc_ln52_51_fu_761_p4 : 8'd0);

assign out_data_sroa_32136_0_0_fu_823_p3 = ((icmp_ln51_27_fu_797_p2[0:0] == 1'b1) ? trunc_ln52_53_fu_803_p4 : 8'd0);

assign out_data_sroa_35140_0_0_fu_865_p3 = ((icmp_ln51_28_fu_839_p2[0:0] == 1'b1) ? trunc_ln52_55_fu_845_p4 : 8'd0);

assign out_data_sroa_5100_0_0_fu_445_p3 = ((icmp_ln51_18_fu_419_p2[0:0] == 1'b1) ? trunc_ln52_35_fu_425_p4 : 8'd0);

assign out_data_sroa_8104_0_0_fu_487_p3 = ((icmp_ln51_19_fu_461_p2[0:0] == 1'b1) ? trunc_ln52_37_fu_467_p4 : 8'd0);

assign start_out = real_start;

assign storemerge_fu_873_p3 = ((icmp_ln51_28_fu_839_p2[0:0] == 1'b1) ? trunc_ln52_56_fu_855_p4 : 2'd0);

assign tmp_17_fu_917_p4 = {{layer3_out_dout[358:351]}};

assign tmp_18_fu_935_p4 = {{layer3_out_dout[321:314]}};

assign tmp_19_fu_953_p4 = {{layer3_out_dout[284:277]}};

assign tmp_20_fu_971_p4 = {{layer3_out_dout[247:240]}};

assign tmp_21_fu_989_p4 = {{layer3_out_dout[210:203]}};

assign tmp_22_fu_1007_p4 = {{layer3_out_dout[173:166]}};

assign tmp_23_fu_1025_p4 = {{layer3_out_dout[136:129]}};

assign tmp_24_fu_1043_p4 = {{layer3_out_dout[99:92]}};

assign tmp_25_fu_1061_p4 = {{layer3_out_dout[62:55]}};

assign tmp_26_fu_1079_p4 = {{layer3_out_dout[25:18]}};

assign tmp_fu_881_p4 = {{layer3_out_dout[432:425]}};

assign tmp_s_fu_899_p4 = {{layer3_out_dout[395:388]}};

assign trunc_ln2_fu_383_p4 = {{layer3_out_dout[17:10]}};

assign trunc_ln44_17_fu_277_p4 = {{layer3_out_dout[110:74]}};

assign trunc_ln44_18_fu_287_p4 = {{layer3_out_dout[147:111]}};

assign trunc_ln44_19_fu_297_p4 = {{layer3_out_dout[184:148]}};

assign trunc_ln44_20_fu_307_p4 = {{layer3_out_dout[221:185]}};

assign trunc_ln44_21_fu_317_p4 = {{layer3_out_dout[258:222]}};

assign trunc_ln44_22_fu_327_p4 = {{layer3_out_dout[295:259]}};

assign trunc_ln44_23_fu_337_p4 = {{layer3_out_dout[332:296]}};

assign trunc_ln44_24_fu_347_p4 = {{layer3_out_dout[369:333]}};

assign trunc_ln44_25_fu_357_p4 = {{layer3_out_dout[406:370]}};

assign trunc_ln44_26_fu_367_p4 = {{layer3_out_dout[443:407]}};

assign trunc_ln44_fu_263_p1 = layer3_out_dout[36:0];

assign trunc_ln44_s_fu_267_p4 = {{layer3_out_dout[73:37]}};

assign trunc_ln52_35_fu_425_p4 = {{layer3_out_dout[54:47]}};

assign trunc_ln52_36_fu_435_p4 = {{layer3_out_dout[64:63]}};

assign trunc_ln52_37_fu_467_p4 = {{layer3_out_dout[91:84]}};

assign trunc_ln52_38_fu_477_p4 = {{layer3_out_dout[101:100]}};

assign trunc_ln52_39_fu_509_p4 = {{layer3_out_dout[128:121]}};

assign trunc_ln52_40_fu_519_p4 = {{layer3_out_dout[138:137]}};

assign trunc_ln52_41_fu_551_p4 = {{layer3_out_dout[165:158]}};

assign trunc_ln52_42_fu_561_p4 = {{layer3_out_dout[175:174]}};

assign trunc_ln52_43_fu_593_p4 = {{layer3_out_dout[202:195]}};

assign trunc_ln52_44_fu_603_p4 = {{layer3_out_dout[212:211]}};

assign trunc_ln52_45_fu_635_p4 = {{layer3_out_dout[239:232]}};

assign trunc_ln52_46_fu_645_p4 = {{layer3_out_dout[249:248]}};

assign trunc_ln52_47_fu_677_p4 = {{layer3_out_dout[276:269]}};

assign trunc_ln52_48_fu_687_p4 = {{layer3_out_dout[286:285]}};

assign trunc_ln52_49_fu_719_p4 = {{layer3_out_dout[313:306]}};

assign trunc_ln52_50_fu_729_p4 = {{layer3_out_dout[323:322]}};

assign trunc_ln52_51_fu_761_p4 = {{layer3_out_dout[350:343]}};

assign trunc_ln52_52_fu_771_p4 = {{layer3_out_dout[360:359]}};

assign trunc_ln52_53_fu_803_p4 = {{layer3_out_dout[387:380]}};

assign trunc_ln52_54_fu_813_p4 = {{layer3_out_dout[397:396]}};

assign trunc_ln52_55_fu_845_p4 = {{layer3_out_dout[424:417]}};

assign trunc_ln52_56_fu_855_p4 = {{layer3_out_dout[434:433]}};

assign trunc_ln52_s_fu_393_p4 = {{layer3_out_dout[27:26]}};

endmodule //myproject_relu_array_ap_fixed_12u_array_ap_fixed_18_8_5_3_0_12u_relu_config4_s
