// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
input  [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
output  [17:0] ap_return_0;
output  [17:0] ap_return_1;
output  [17:0] ap_return_2;
output  [17:0] ap_return_3;
output  [17:0] ap_return_4;
output  [17:0] ap_return_5;
output  [17:0] ap_return_6;
output  [17:0] ap_return_7;
output  [17:0] ap_return_8;
output  [17:0] ap_return_9;
output  [17:0] ap_return_10;
output  [17:0] ap_return_11;

reg ap_idle;
reg[17:0] ap_return_0;
reg[17:0] ap_return_1;
reg[17:0] ap_return_2;
reg[17:0] ap_return_3;
reg[17:0] ap_return_4;
reg[17:0] ap_return_5;
reg[17:0] ap_return_6;
reg[17:0] ap_return_7;
reg[17:0] ap_return_8;
reg[17:0] ap_return_9;
reg[17:0] ap_return_10;
reg[17:0] ap_return_11;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln135_fu_664_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] outidx_63_address0;
wire   [2:0] outidx_63_q0;
wire   [5:0] w2_address0;
wire   [28:0] w2_q0;
reg   [0:0] do_init_reg_172;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] w_index33_reg_187;
reg   [31:0] in_index34_reg_326;
reg   [23:0] acc32_reg_340;
reg   [23:0] acc_5830_reg_354;
reg   [23:0] acc_5928_reg_368;
reg   [23:0] acc_6026_reg_382;
reg   [23:0] acc_6124_reg_396;
reg   [23:0] acc_6222_reg_410;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520;
reg   [23:0] acc_6320_reg_532;
reg   [23:0] acc_6418_reg_546;
reg   [23:0] acc_6516_reg_560;
reg   [23:0] acc_6614_reg_574;
reg   [23:0] acc_6712_reg_588;
reg   [23:0] acc_6810_reg_602;
wire   [5:0] w_index_fu_658_p2;
reg   [5:0] w_index_reg_1407;
reg   [0:0] icmp_ln135_reg_1412;
reg   [0:0] icmp_ln135_reg_1412_pp0_iter1_reg;
reg   [2:0] out_index_reg_1416;
wire   [0:0] icmp_ln144_13_fu_802_p2;
reg   [0:0] icmp_ln144_13_reg_1422;
wire   [0:0] icmp_ln144_fu_808_p2;
reg   [0:0] icmp_ln144_reg_1428;
wire   [0:0] icmp_ln144_14_fu_814_p2;
reg   [0:0] icmp_ln144_14_reg_1434;
wire   [0:0] icmp_ln144_15_fu_820_p2;
reg   [0:0] icmp_ln144_15_reg_1441;
wire   [0:0] icmp_ln144_16_fu_826_p2;
reg   [0:0] icmp_ln144_16_reg_1448;
reg   [20:0] trunc_ln144_8_reg_1455;
wire   [23:0] acc_37_fu_906_p3;
reg   [23:0] acc_37_reg_1460;
wire   [23:0] acc_36_fu_914_p3;
reg   [23:0] acc_36_reg_1466;
wire   [23:0] acc_35_fu_922_p3;
reg   [23:0] acc_35_reg_1472;
wire   [23:0] acc_34_fu_930_p3;
reg   [23:0] acc_34_reg_1478;
wire   [23:0] acc_33_fu_938_p3;
reg   [23:0] acc_33_reg_1484;
wire   [23:0] acc_fu_958_p3;
reg   [23:0] acc_reg_1490;
wire   [31:0] in_index_fu_978_p3;
reg   [31:0] in_index_reg_1496;
wire   [23:0] acc_43_fu_1098_p3;
wire   [23:0] acc_42_fu_1125_p3;
wire   [23:0] acc_41_fu_1133_p3;
wire   [23:0] acc_40_fu_1140_p3;
wire   [23:0] acc_39_fu_1147_p3;
wire   [23:0] acc_38_fu_1154_p3;
reg   [0:0] ap_phi_mux_do_init_phi_fu_175_p6;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [5:0] ap_phi_mux_w_index33_phi_fu_190_p6;
reg   [31:0] ap_phi_mux_in_index34_phi_fu_330_p6;
reg    ap_loop_init_pp0_iter1_reg;
reg   [23:0] ap_phi_mux_acc32_phi_fu_344_p6;
reg   [23:0] ap_phi_mux_acc_5830_phi_fu_358_p6;
reg   [23:0] ap_phi_mux_acc_5928_phi_fu_372_p6;
reg   [23:0] ap_phi_mux_acc_6026_phi_fu_386_p6;
reg   [23:0] ap_phi_mux_acc_6124_phi_fu_400_p6;
reg   [23:0] ap_phi_mux_acc_6222_phi_fu_414_p6;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_phi_fu_428_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_phi_fu_440_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_phi_fu_452_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_phi_fu_464_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_phi_fu_476_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_phi_fu_488_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_500_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_512_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508;
reg   [17:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_524_p4;
wire   [17:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520;
reg   [17:0] ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520;
reg   [23:0] ap_phi_mux_acc_6320_phi_fu_536_p6;
reg    ap_loop_init_pp0_iter2_reg;
reg   [23:0] ap_phi_mux_acc_6418_phi_fu_550_p6;
reg   [23:0] ap_phi_mux_acc_6516_phi_fu_564_p6;
reg   [23:0] ap_phi_mux_acc_6614_phi_fu_578_p6;
reg   [23:0] ap_phi_mux_acc_6712_phi_fu_592_p6;
reg   [23:0] ap_phi_mux_acc_6810_phi_fu_606_p6;
wire   [63:0] zext_ln135_fu_652_p1;
reg    outidx_63_ce0_local;
reg    w2_ce0_local;
wire   [17:0] a_fu_674_p19;
wire   [3:0] a_fu_674_p20;
wire  signed [17:0] w_fu_718_p1;
wire  signed [17:0] a_fu_674_p21;
wire   [31:0] mul_ln144_fu_734_p2;
wire   [23:0] tmp_i_fu_750_p13;
wire  signed [23:0] tmp_i_fu_750_p15;
wire  signed [23:0] trunc_ln5_fu_740_p4;
wire  signed [24:0] sext_ln144_fu_782_p1;
wire  signed [24:0] sext_ln144_8_fu_786_p1;
wire   [24:0] sub_ln144_fu_796_p2;
wire   [0:0] icmp_ln144_17_fu_832_p2;
wire   [0:0] or_ln144_fu_838_p2;
wire   [0:0] or_ln144_30_fu_850_p2;
wire   [0:0] or_ln144_31_fu_856_p2;
wire   [0:0] or_ln144_29_fu_844_p2;
wire   [0:0] or_ln144_32_fu_862_p2;
wire  signed [10:0] tmp_fu_876_p4;
wire   [28:0] mul_ln144_3_fu_890_p2;
wire   [23:0] acc_45_fu_790_p2;
wire   [0:0] or_ln144_33_fu_946_p2;
wire   [0:0] or_ln144_34_fu_952_p2;
wire   [23:0] acc_44_fu_868_p3;
wire   [31:0] in_index_3_fu_966_p2;
wire   [0:0] icmp_ln154_fu_972_p2;
wire   [23:0] tmp_i_115_fu_986_p13;
wire   [23:0] tmp_i_115_fu_986_p15;
wire  signed [24:0] sext_ln144_10_fu_1021_p1;
wire  signed [24:0] sext_ln144_9_fu_1017_p1;
wire   [24:0] add_ln144_fu_1024_p2;
wire   [0:0] icmp_ln144_5_fu_1030_p2;
wire   [0:0] xor_ln144_fu_1041_p2;
wire   [0:0] or_ln144_35_fu_1047_p2;
wire   [0:0] icmp_ln144_18_fu_1036_p2;
wire   [0:0] or_ln144_37_fu_1057_p2;
wire   [0:0] or_ln144_38_fu_1062_p2;
wire   [0:0] or_ln144_36_fu_1052_p2;
wire   [0:0] or_ln144_39_fu_1067_p2;
wire   [0:0] and_ln144_fu_1081_p2;
wire   [23:0] acc_48_fu_1094_p1;
wire   [23:0] acc_47_fu_1073_p3;
wire   [0:0] or_ln144_41_fu_1109_p2;
wire   [0:0] or_ln144_42_fu_1114_p2;
wire   [0:0] or_ln144_40_fu_1105_p2;
wire   [0:0] or_ln144_43_fu_1119_p2;
wire   [23:0] acc_46_fu_1086_p3;
reg   [17:0] ap_return_0_preg;
reg   [17:0] ap_return_1_preg;
reg   [17:0] ap_return_2_preg;
reg   [17:0] ap_return_3_preg;
reg   [17:0] ap_return_4_preg;
reg   [17:0] ap_return_5_preg;
reg   [17:0] ap_return_6_preg;
reg   [17:0] ap_return_7_preg;
reg   [17:0] ap_return_8_preg;
reg   [17:0] ap_return_9_preg;
reg   [17:0] ap_return_10_preg;
reg   [17:0] ap_return_11_preg;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_178;
reg    ap_condition_200;
wire   [3:0] a_fu_674_p1;
wire   [3:0] a_fu_674_p3;
wire   [3:0] a_fu_674_p5;
wire   [3:0] a_fu_674_p7;
wire   [3:0] a_fu_674_p9;
wire   [3:0] a_fu_674_p11;
wire   [3:0] a_fu_674_p13;
wire   [3:0] a_fu_674_p15;
wire  signed [3:0] a_fu_674_p17;
wire   [2:0] tmp_i_fu_750_p1;
wire   [2:0] tmp_i_fu_750_p3;
wire   [2:0] tmp_i_fu_750_p5;
wire   [2:0] tmp_i_fu_750_p7;
wire  signed [2:0] tmp_i_fu_750_p9;
wire  signed [2:0] tmp_i_fu_750_p11;
wire   [2:0] tmp_i_115_fu_986_p1;
wire   [2:0] tmp_i_115_fu_986_p3;
wire   [2:0] tmp_i_115_fu_986_p5;
wire   [2:0] tmp_i_115_fu_986_p7;
wire  signed [2:0] tmp_i_115_fu_986_p9;
wire  signed [2:0] tmp_i_115_fu_986_p11;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_return_0_preg = 18'd0;
#0 ap_return_1_preg = 18'd0;
#0 ap_return_2_preg = 18'd0;
#0 ap_return_3_preg = 18'd0;
#0 ap_return_4_preg = 18'd0;
#0 ap_return_5_preg = 18'd0;
#0 ap_return_6_preg = 18'd0;
#0 ap_return_7_preg = 18'd0;
#0 ap_return_8_preg = 18'd0;
#0 ap_return_9_preg = 18'd0;
#0 ap_return_10_preg = 18'd0;
#0 ap_return_11_preg = 18'd0;
#0 ap_done_reg = 1'b0;
end

myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_outdEe #(
    .DataWidth( 3 ),
    .AddressRange( 54 ),
    .AddressWidth( 6 ))
outidx_63_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_63_address0),
    .ce0(outidx_63_ce0_local),
    .q0(outidx_63_q0)
);

myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_w2_eOg #(
    .DataWidth( 29 ),
    .AddressRange( 54 ),
    .AddressWidth( 6 ))
w2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_address0),
    .ce0(w2_ce0_local),
    .q0(w2_q0)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_19_4_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 18 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 18 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 18 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 18 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 18 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 18 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 18 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
sparsemux_19_4_18_1_1_U18(
    .din0(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_524_p4),
    .din1(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_512_p4),
    .din2(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_500_p4),
    .din3(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_phi_fu_488_p4),
    .din4(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_phi_fu_476_p4),
    .din5(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_phi_fu_464_p4),
    .din6(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_phi_fu_452_p4),
    .din7(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_phi_fu_440_p4),
    .din8(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_phi_fu_428_p4),
    .def(a_fu_674_p19),
    .sel(a_fu_674_p20),
    .dout(a_fu_674_p21)
);

myproject_mul_18s_18s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 32 ))
mul_18s_18s_32_1_1_U19(
    .din0(w_fu_718_p1),
    .din1(a_fu_674_p21),
    .dout(mul_ln144_fu_734_p2)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_13_3_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 24 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 24 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 24 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 24 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 24 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 24 ),
    .def_WIDTH( 24 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 24 ))
sparsemux_13_3_24_1_1_U20(
    .din0(ap_phi_mux_acc32_phi_fu_344_p6),
    .din1(ap_phi_mux_acc_5830_phi_fu_358_p6),
    .din2(ap_phi_mux_acc_5928_phi_fu_372_p6),
    .din3(ap_phi_mux_acc_6026_phi_fu_386_p6),
    .din4(ap_phi_mux_acc_6124_phi_fu_400_p6),
    .din5(ap_phi_mux_acc_6222_phi_fu_414_p6),
    .def(tmp_i_fu_750_p13),
    .sel(outidx_63_q0),
    .dout(tmp_i_fu_750_p15)
);

myproject_mul_18s_11s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11s_29_1_1_U21(
    .din0(a_fu_674_p21),
    .din1(tmp_fu_876_p4),
    .dout(mul_ln144_3_fu_890_p2)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_13_3_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 24 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 24 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 24 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 24 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 24 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 24 ),
    .def_WIDTH( 24 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 24 ))
sparsemux_13_3_24_1_1_U22(
    .din0(ap_phi_mux_acc_6320_phi_fu_536_p6),
    .din1(ap_phi_mux_acc_6418_phi_fu_550_p6),
    .din2(ap_phi_mux_acc_6516_phi_fu_564_p6),
    .din3(ap_phi_mux_acc_6614_phi_fu_578_p6),
    .din4(ap_phi_mux_acc_6712_phi_fu_592_p6),
    .din5(ap_phi_mux_acc_6810_phi_fu_606_p6),
    .def(tmp_i_115_fu_986_p13),
    .sel(out_index_reg_1416),
    .dout(tmp_i_115_fu_986_p15)
);

myproject_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_0_preg <= {{acc_reg_1490[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_10_preg <= {{acc_42_fu_1125_p3[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_11_preg <= {{acc_43_fu_1098_p3[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_1_preg <= {{acc_33_reg_1484[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_2_preg <= {{acc_34_reg_1478[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_3_preg <= {{acc_35_reg_1472[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_4_preg <= {{acc_36_reg_1466[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_5_preg <= {{acc_37_reg_1460[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_6_preg <= {{acc_38_fu_1154_p3[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_7_preg <= {{acc_39_fu_1147_p3[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_8_preg <= {{acc_40_fu_1140_p3[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 18'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
            ap_return_9_preg <= {{acc_41_fu_1133_p3[19:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        acc32_reg_340 <= acc_reg_1490;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        acc32_reg_340 <= 24'd332;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        acc_5830_reg_354 <= acc_33_reg_1484;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        acc_5830_reg_354 <= 24'd140;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        acc_5928_reg_368 <= acc_34_reg_1478;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        acc_5928_reg_368 <= 24'd992;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        acc_6026_reg_382 <= acc_35_reg_1472;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        acc_6026_reg_382 <= 24'd124;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        acc_6124_reg_396 <= acc_36_reg_1466;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        acc_6124_reg_396 <= 24'd16777180;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        acc_6222_reg_410 <= acc_37_reg_1460;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        acc_6222_reg_410 <= 24'd1292;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) begin
            acc_6320_reg_532 <= 24'd16776940;
        end else if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0)) begin
            acc_6320_reg_532 <= acc_38_fu_1154_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) begin
            acc_6418_reg_546 <= 24'd16776680;
        end else if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0)) begin
            acc_6418_reg_546 <= acc_39_fu_1147_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) begin
            acc_6516_reg_560 <= 24'd932;
        end else if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0)) begin
            acc_6516_reg_560 <= acc_40_fu_1140_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) begin
            acc_6614_reg_574 <= 24'd120;
        end else if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0)) begin
            acc_6614_reg_574 <= acc_41_fu_1133_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) begin
            acc_6712_reg_588 <= 24'd100;
        end else if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0)) begin
            acc_6712_reg_588 <= acc_42_fu_1125_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) begin
            acc_6810_reg_602 <= 24'd1172;
        end else if ((icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0)) begin
            acc_6810_reg_602 <= acc_43_fu_1098_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if ((ap_phi_mux_do_init_phi_fu_175_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1412 == 1'd0))) begin
        do_init_reg_172 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1412 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        do_init_reg_172 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        in_index34_reg_326 <= in_index_reg_1496;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_index34_reg_326 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_200)) begin
        if ((do_init_reg_172 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520 <= ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1412 == 1'd0))) begin
        w_index33_reg_187 <= w_index_reg_1407;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1412 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        w_index33_reg_187 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_33_reg_1484 <= acc_33_fu_938_p3;
        acc_34_reg_1478 <= acc_34_fu_930_p3;
        acc_35_reg_1472 <= acc_35_fu_922_p3;
        acc_36_reg_1466 <= acc_36_fu_914_p3;
        acc_37_reg_1460 <= acc_37_fu_906_p3;
        acc_reg_1490 <= acc_fu_958_p3;
        in_index_reg_1496 <= in_index_fu_978_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
        icmp_ln135_reg_1412 <= icmp_ln135_fu_664_p2;
        icmp_ln135_reg_1412_pp0_iter1_reg <= icmp_ln135_reg_1412;
        icmp_ln144_13_reg_1422 <= icmp_ln144_13_fu_802_p2;
        icmp_ln144_14_reg_1434 <= icmp_ln144_14_fu_814_p2;
        icmp_ln144_15_reg_1441 <= icmp_ln144_15_fu_820_p2;
        icmp_ln144_16_reg_1448 <= icmp_ln144_16_fu_826_p2;
        icmp_ln144_reg_1428 <= icmp_ln144_fu_808_p2;
        out_index_reg_1416 <= outidx_63_q0;
        trunc_ln144_8_reg_1455 <= {{mul_ln144_3_fu_890_p2[28:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1407 <= w_index_fu_658_p2;
    end
end

always @ (*) begin
    if (((icmp_ln135_fu_664_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc32_phi_fu_344_p6 = acc_reg_1490;
    end else if ((((ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)))) begin
        ap_phi_mux_acc32_phi_fu_344_p6 = 24'd332;
    end else begin
        ap_phi_mux_acc32_phi_fu_344_p6 = acc32_reg_340;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_5830_phi_fu_358_p6 = acc_33_reg_1484;
    end else if ((((ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)))) begin
        ap_phi_mux_acc_5830_phi_fu_358_p6 = 24'd140;
    end else begin
        ap_phi_mux_acc_5830_phi_fu_358_p6 = acc_5830_reg_354;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_5928_phi_fu_372_p6 = acc_34_reg_1478;
    end else if ((((ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)))) begin
        ap_phi_mux_acc_5928_phi_fu_372_p6 = 24'd992;
    end else begin
        ap_phi_mux_acc_5928_phi_fu_372_p6 = acc_5928_reg_368;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_6026_phi_fu_386_p6 = acc_35_reg_1472;
    end else if ((((ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)))) begin
        ap_phi_mux_acc_6026_phi_fu_386_p6 = 24'd124;
    end else begin
        ap_phi_mux_acc_6026_phi_fu_386_p6 = acc_6026_reg_382;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_6124_phi_fu_400_p6 = acc_36_reg_1466;
    end else if ((((ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)))) begin
        ap_phi_mux_acc_6124_phi_fu_400_p6 = 24'd16777180;
    end else begin
        ap_phi_mux_acc_6124_phi_fu_400_p6 = acc_6124_reg_396;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_6222_phi_fu_414_p6 = acc_37_reg_1460;
    end else if ((((ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)))) begin
        ap_phi_mux_acc_6222_phi_fu_414_p6 = 24'd1292;
    end else begin
        ap_phi_mux_acc_6222_phi_fu_414_p6 = acc_6222_reg_410;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_acc_6320_phi_fu_536_p6 = 24'd16776940;
    end else begin
        ap_phi_mux_acc_6320_phi_fu_536_p6 = acc_6320_reg_532;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_acc_6418_phi_fu_550_p6 = 24'd16776680;
    end else begin
        ap_phi_mux_acc_6418_phi_fu_550_p6 = acc_6418_reg_546;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_acc_6516_phi_fu_564_p6 = 24'd932;
    end else begin
        ap_phi_mux_acc_6516_phi_fu_564_p6 = acc_6516_reg_560;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_acc_6614_phi_fu_578_p6 = 24'd120;
    end else begin
        ap_phi_mux_acc_6614_phi_fu_578_p6 = acc_6614_reg_574;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_acc_6712_phi_fu_592_p6 = 24'd100;
    end else begin
        ap_phi_mux_acc_6712_phi_fu_592_p6 = acc_6712_reg_588;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_acc_6810_phi_fu_606_p6 = 24'd1172;
    end else begin
        ap_phi_mux_acc_6810_phi_fu_606_p6 = acc_6810_reg_602;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1412 == 1'd0))) begin
        ap_phi_mux_do_init_phi_fu_175_p6 = 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1412 == 1'd1)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_do_init_phi_fu_175_p6 = 1'd1;
    end else begin
        ap_phi_mux_do_init_phi_fu_175_p6 = do_init_reg_172;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_in_index34_phi_fu_330_p6 = in_index_reg_1496;
    end else if ((((ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1)))) begin
        ap_phi_mux_in_index34_phi_fu_330_p6 = 32'd0;
    end else begin
        ap_phi_mux_in_index34_phi_fu_330_p6 = in_index34_reg_326;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_phi_fu_428_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_phi_fu_428_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_phi_fu_440_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_phi_fu_440_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_phi_fu_452_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_phi_fu_452_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_phi_fu_464_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_phi_fu_464_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_phi_fu_476_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_phi_fu_476_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_phi_fu_488_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_phi_fu_488_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_500_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_500_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_512_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_512_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508;
    end
end

always @ (*) begin
    if ((do_init_reg_172 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_524_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_524_p4 = ap_phi_reg_pp0_iter1_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1412 == 1'd0))) begin
        ap_phi_mux_w_index33_phi_fu_190_p6 = w_index_reg_1407;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1412 == 1'd1)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_w_index33_phi_fu_190_p6 = 6'd0;
    end else begin
        ap_phi_mux_w_index33_phi_fu_190_p6 = w_index33_reg_187;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_0 = {{acc_reg_1490[19:2]}};
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_1 = {{acc_33_reg_1484[19:2]}};
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_10 = {{acc_42_fu_1125_p3[19:2]}};
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_11 = {{acc_43_fu_1098_p3[19:2]}};
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_2 = {{acc_34_reg_1478[19:2]}};
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_3 = {{acc_35_reg_1472[19:2]}};
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_4 = {{acc_36_reg_1466[19:2]}};
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_5 = {{acc_37_reg_1460[19:2]}};
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_6 = {{acc_38_fu_1154_p3[19:2]}};
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_7 = {{acc_39_fu_1147_p3[19:2]}};
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_8 = {{acc_40_fu_1140_p3[19:2]}};
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1412_pp0_iter1_reg == 1'd1))) begin
        ap_return_9 = {{acc_41_fu_1133_p3[19:2]}};
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_63_ce0_local = 1'b1;
    end else begin
        outidx_63_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_ce0_local = 1'b1;
    end else begin
        w2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_674_p19 = 'bx;

assign a_fu_674_p20 = ap_phi_mux_in_index34_phi_fu_330_p6[3:0];

assign acc_33_fu_938_p3 = ((icmp_ln144_16_fu_826_p2[0:0] == 1'b1) ? acc_45_fu_790_p2 : ap_phi_mux_acc_5830_phi_fu_358_p6);

assign acc_34_fu_930_p3 = ((icmp_ln144_15_fu_820_p2[0:0] == 1'b1) ? acc_45_fu_790_p2 : ap_phi_mux_acc_5928_phi_fu_372_p6);

assign acc_35_fu_922_p3 = ((icmp_ln144_14_fu_814_p2[0:0] == 1'b1) ? acc_45_fu_790_p2 : ap_phi_mux_acc_6026_phi_fu_386_p6);

assign acc_36_fu_914_p3 = ((icmp_ln144_fu_808_p2[0:0] == 1'b1) ? acc_45_fu_790_p2 : ap_phi_mux_acc_6124_phi_fu_400_p6);

assign acc_37_fu_906_p3 = ((icmp_ln144_13_fu_802_p2[0:0] == 1'b1) ? acc_45_fu_790_p2 : ap_phi_mux_acc_6222_phi_fu_414_p6);

assign acc_38_fu_1154_p3 = ((icmp_ln144_18_fu_1036_p2[0:0] == 1'b1) ? acc_48_fu_1094_p1 : ap_phi_mux_acc_6320_phi_fu_536_p6);

assign acc_39_fu_1147_p3 = ((icmp_ln144_16_reg_1448[0:0] == 1'b1) ? acc_48_fu_1094_p1 : ap_phi_mux_acc_6418_phi_fu_550_p6);

assign acc_40_fu_1140_p3 = ((icmp_ln144_15_reg_1441[0:0] == 1'b1) ? acc_48_fu_1094_p1 : ap_phi_mux_acc_6516_phi_fu_564_p6);

assign acc_41_fu_1133_p3 = ((icmp_ln144_14_reg_1434[0:0] == 1'b1) ? acc_48_fu_1094_p1 : ap_phi_mux_acc_6614_phi_fu_578_p6);

assign acc_42_fu_1125_p3 = ((or_ln144_43_fu_1119_p2[0:0] == 1'b1) ? acc_46_fu_1086_p3 : acc_48_fu_1094_p1);

assign acc_43_fu_1098_p3 = ((icmp_ln144_13_reg_1422[0:0] == 1'b1) ? acc_48_fu_1094_p1 : acc_47_fu_1073_p3);

assign acc_44_fu_868_p3 = ((or_ln144_32_fu_862_p2[0:0] == 1'b1) ? ap_phi_mux_acc32_phi_fu_344_p6 : 24'd0);

assign acc_45_fu_790_p2 = ($signed(trunc_ln5_fu_740_p4) + $signed(tmp_i_fu_750_p15));

assign acc_46_fu_1086_p3 = ((and_ln144_fu_1081_p2[0:0] == 1'b1) ? 24'd0 : ap_phi_mux_acc_6712_phi_fu_592_p6);

assign acc_47_fu_1073_p3 = ((or_ln144_39_fu_1067_p2[0:0] == 1'b1) ? ap_phi_mux_acc_6810_phi_fu_606_p6 : 24'd0);

assign acc_48_fu_1094_p1 = add_ln144_fu_1024_p2[23:0];

assign acc_fu_958_p3 = ((or_ln144_34_fu_952_p2[0:0] == 1'b1) ? acc_44_fu_868_p3 : acc_45_fu_790_p2);

assign add_ln144_fu_1024_p2 = ($signed(sext_ln144_10_fu_1021_p1) + $signed(sext_ln144_9_fu_1017_p1));

assign and_ln144_fu_1081_p2 = (icmp_ln144_reg_1428 & icmp_ln144_5_fu_1030_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_178 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_200 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_reg_424 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_reg_436 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_reg_448 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_reg_460 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_59_reg_472 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_60_reg_484 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_496 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_508 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_520 = 'bx;

assign ap_ready = ap_ready_sig;

assign icmp_ln135_fu_664_p2 = ((ap_phi_mux_w_index33_phi_fu_190_p6 == 6'd53) ? 1'b1 : 1'b0);

assign icmp_ln144_13_fu_802_p2 = ((outidx_63_q0 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln144_14_fu_814_p2 = ((outidx_63_q0 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln144_15_fu_820_p2 = ((outidx_63_q0 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln144_16_fu_826_p2 = ((outidx_63_q0 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln144_17_fu_832_p2 = ((sext_ln144_8_fu_786_p1 != sub_ln144_fu_796_p2) ? 1'b1 : 1'b0);

assign icmp_ln144_18_fu_1036_p2 = ((out_index_reg_1416 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln144_5_fu_1030_p2 = ((add_ln144_fu_1024_p2 == 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_808_p2 = ((outidx_63_q0 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_972_p2 = (($signed(in_index_3_fu_966_p2) > $signed(32'd8)) ? 1'b1 : 1'b0);

assign in_index_3_fu_966_p2 = (ap_phi_mux_in_index34_phi_fu_330_p6 + 32'd1);

assign in_index_fu_978_p3 = ((icmp_ln154_fu_972_p2[0:0] == 1'b1) ? 32'd0 : in_index_3_fu_966_p2);

assign or_ln144_29_fu_844_p2 = (or_ln144_fu_838_p2 | icmp_ln144_13_fu_802_p2);

assign or_ln144_30_fu_850_p2 = (icmp_ln144_fu_808_p2 | icmp_ln144_14_fu_814_p2);

assign or_ln144_31_fu_856_p2 = (or_ln144_30_fu_850_p2 | icmp_ln144_15_fu_820_p2);

assign or_ln144_32_fu_862_p2 = (or_ln144_31_fu_856_p2 | or_ln144_29_fu_844_p2);

assign or_ln144_33_fu_946_p2 = (icmp_ln144_16_fu_826_p2 | icmp_ln144_13_fu_802_p2);

assign or_ln144_34_fu_952_p2 = (or_ln144_33_fu_946_p2 | or_ln144_31_fu_856_p2);

assign or_ln144_35_fu_1047_p2 = (xor_ln144_fu_1041_p2 | icmp_ln144_14_reg_1434);

assign or_ln144_36_fu_1052_p2 = (or_ln144_35_fu_1047_p2 | icmp_ln144_reg_1428);

assign or_ln144_37_fu_1057_p2 = (icmp_ln144_18_fu_1036_p2 | icmp_ln144_16_reg_1448);

assign or_ln144_38_fu_1062_p2 = (or_ln144_37_fu_1057_p2 | icmp_ln144_15_reg_1441);

assign or_ln144_39_fu_1067_p2 = (or_ln144_38_fu_1062_p2 | or_ln144_36_fu_1052_p2);

assign or_ln144_40_fu_1105_p2 = (icmp_ln144_15_reg_1441 | icmp_ln144_14_reg_1434);

assign or_ln144_41_fu_1109_p2 = (icmp_ln144_18_fu_1036_p2 | icmp_ln144_13_reg_1422);

assign or_ln144_42_fu_1114_p2 = (or_ln144_41_fu_1109_p2 | icmp_ln144_16_reg_1448);

assign or_ln144_43_fu_1119_p2 = (or_ln144_42_fu_1114_p2 | or_ln144_40_fu_1105_p2);

assign or_ln144_fu_838_p2 = (icmp_ln144_17_fu_832_p2 | icmp_ln144_16_fu_826_p2);

assign outidx_63_address0 = zext_ln135_fu_652_p1;

assign sext_ln144_10_fu_1021_p1 = $signed(trunc_ln144_8_reg_1455);

assign sext_ln144_8_fu_786_p1 = trunc_ln5_fu_740_p4;

assign sext_ln144_9_fu_1017_p1 = $signed(tmp_i_115_fu_986_p15);

assign sext_ln144_fu_782_p1 = tmp_i_fu_750_p15;

assign sub_ln144_fu_796_p2 = ($signed(25'd0) - $signed(sext_ln144_fu_782_p1));

assign tmp_fu_876_p4 = {{w2_q0[28:18]}};

assign tmp_i_115_fu_986_p13 = 'bx;

assign tmp_i_fu_750_p13 = 'bx;

assign trunc_ln5_fu_740_p4 = {{mul_ln144_fu_734_p2[31:8]}};

assign w2_address0 = zext_ln135_fu_652_p1;

assign w_fu_718_p1 = w2_q0[17:0];

assign w_index_fu_658_p2 = (ap_phi_mux_w_index33_phi_fu_190_p6 + 6'd1);

assign xor_ln144_fu_1041_p2 = (icmp_ln144_5_fu_1030_p2 ^ 1'd1);

assign zext_ln135_fu_652_p1 = ap_phi_mux_w_index33_phi_fu_190_p6;

endmodule //myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s
