// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_12u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_elem_0_0_0_0_0_val,
        layer2_out_din,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_full_n,
        layer2_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] in_elem_0_0_0_0_0_val;
output  [215:0] layer2_out_din;
input  [10:0] layer2_out_num_data_valid;
input  [10:0] layer2_out_fifo_cap;
input   layer2_out_full_n;
output   layer2_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
reg   [17:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
reg   [31:0] sX_2;
reg   [31:0] sY_2;
reg   [31:0] pY_2;
reg   [31:0] pX_2;
reg    layer2_out_blk_n;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln284_reg_396;
reg   [0:0] and_ln284_1_reg_410;
wire   [0:0] icmp_ln284_fu_153_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] and_ln284_1_fu_215_p2;
reg    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_start;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_done;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_idle;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_ready;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld;
wire   [17:0] call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_done;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_idle;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_ready;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_0;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_1;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_2;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_3;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_4;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_5;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_6;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_7;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_8;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_9;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_10;
wire   [17:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_11;
wire   [31:0] add_ln313_fu_375_p2;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_88_p4;
reg    ap_predicate_op36_write_state3;
reg    ap_block_state3;
reg    ap_predicate_op22_call_state3;
reg    ap_block_state3_on_subcall_done;
wire   [0:0] icmp_ln303_fu_303_p2;
wire   [0:0] icmp_ln307_fu_350_p2;
reg    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start_reg;
wire   [31:0] add_ln318_fu_322_p2;
wire   [31:0] add_ln307_fu_345_p2;
wire   [31:0] add_ln303_fu_298_p2;
wire   [215:0] p_0_fu_269_p13;
reg    layer2_out_write_local;
wire   [30:0] tmp_3_fu_177_p4;
wire   [30:0] tmp_4_fu_193_p4;
wire   [0:0] icmp_ln284_4_fu_187_p2;
wire   [0:0] icmp_ln284_5_fu_203_p2;
wire   [0:0] and_ln284_fu_209_p2;
wire   [0:0] icmp_ln284_1_fu_171_p2;
wire   [31:0] select_ln318_fu_315_p3;
wire   [0:0] icmp_ln313_fu_362_p2;
wire   [31:0] select_ln313_fu_367_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_condition_142;
reg    ap_condition_188;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 = 18'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 = 18'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 = 18'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 = 18'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 = 18'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 = 18'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 = 18'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 = 18'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig = 18'd0;
#0 sX_2 = 32'd0;
#0 sY_2 = 32'd0;
#0 pY_2 = 32'd0;
#0 pX_2 = 32'd0;
#0 grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start_reg = 1'b0;
end

myproject_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_start),
    .ap_done(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_done),
    .ap_idle(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_idle),
    .ap_ready(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_ready),
    .in_elem_0_0_0_0_0_val(in_elem_0_0_0_0_0_val),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld)
);

myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start),
    .ap_done(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_done),
    .ap_idle(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_idle),
    .ap_ready(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_ready),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig),
    .ap_return_0(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_0),
    .ap_return_1(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_1),
    .ap_return_2(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_2),
    .ap_return_3(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_3),
    .ap_return_4(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_4),
    .ap_return_5(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_5),
    .ap_return_6(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_6),
    .ap_return_7(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_7),
    .ap_return_8(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_8),
    .ap_return_9(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_9),
    .ap_return_10(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_10),
    .ap_return_11(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_11)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln284_fu_153_p2 == 1'd1) & (1'd1 == and_ln284_1_fu_215_p2) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_142)) begin
        if ((icmp_ln303_fu_303_p2 == 1'd1)) begin
            pX_2 <= 32'd0;
        end else if ((icmp_ln303_fu_303_p2 == 1'd0)) begin
            pX_2 <= add_ln303_fu_298_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_188)) begin
        if ((icmp_ln307_fu_350_p2 == 1'd1)) begin
            pY_2 <= 32'd0;
        end else if ((icmp_ln307_fu_350_p2 == 1'd0)) begin
            pY_2 <= add_ln307_fu_345_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_142)) begin
        if ((icmp_ln303_fu_303_p2 == 1'd1)) begin
            sX_2 <= 32'd0;
        end else if ((icmp_ln303_fu_303_p2 == 1'd0)) begin
            sX_2 <= add_ln318_fu_322_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        and_ln284_1_reg_410 <= and_ln284_1_fu_215_p2;
        icmp_ln284_reg_396 <= icmp_ln284_fu_153_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln303_fu_303_p2 == 1'd1))) begin
        sY_2 <= ap_phi_mux_storemerge_phi_fu_88_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 <= call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln303_fu_303_p2 == 1'd1))) begin
        if ((icmp_ln307_fu_350_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_88_p4 = 32'd0;
        end else if ((icmp_ln307_fu_350_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_phi_fu_88_p4 = add_ln313_fu_375_p2;
        end else begin
            ap_phi_mux_storemerge_phi_fu_88_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_88_p4 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_start = 1'b1;
    end else begin
        call_ln281_shift_line_buffer_array_ap_fixed_18_8_5_3_0_1u_config2_s_fu_95_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln284_1_reg_410) & (icmp_ln284_reg_396 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3) & (ap_predicate_op36_write_state3 == 1'b1))) begin
        layer2_out_write_local = 1'b1;
    end else begin
        layer2_out_write_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln303_fu_298_p2 = (pX_2 + 32'd1);

assign add_ln307_fu_345_p2 = (pY_2 + 32'd1);

assign add_ln313_fu_375_p2 = (sY_2 + select_ln313_fu_367_p3);

assign add_ln318_fu_322_p2 = (sX_2 + select_ln318_fu_315_p3);

assign and_ln284_1_fu_215_p2 = (icmp_ln284_1_fu_171_p2 & and_ln284_fu_209_p2);

assign and_ln284_fu_209_p2 = (icmp_ln284_5_fu_203_p2 & icmp_ln284_4_fu_187_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state3 = ((layer2_out_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_done == 1'b0) & (ap_predicate_op22_call_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_142 = (~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3));
end

always @ (*) begin
    ap_condition_188 = (~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln303_fu_303_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op22_call_state3 = ((1'd1 == and_ln284_1_reg_410) & (icmp_ln284_reg_396 == 1'd1));
end

always @ (*) begin
    ap_predicate_op36_write_state3 = ((1'd1 == and_ln284_1_reg_410) & (icmp_ln284_reg_396 == 1'd1));
end

assign grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start = grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_start_reg;

assign icmp_ln284_1_fu_171_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln284_4_fu_187_p2 = (($signed(tmp_3_fu_177_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_5_fu_203_p2 = (($signed(tmp_4_fu_193_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_fu_153_p2 = ((sX_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln303_fu_303_p2 = ((add_ln303_fu_298_p2 == 32'd103) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_350_p2 = ((add_ln307_fu_345_p2 == 32'd41) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_362_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign layer2_out_din = p_0_fu_269_p13;

assign layer2_out_write = layer2_out_write_local;

assign p_0_fu_269_p13 = {{{{{{{{{{{{grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_11}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_10}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_9}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_8}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_7}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_6}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_5}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_4}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_3}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_2}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_1}}, 
    {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_18_8_5_3_0_config2_mult_s_fu_123_ap_return_0}};

assign select_ln313_fu_367_p3 = ((icmp_ln313_fu_362_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign select_ln318_fu_315_p3 = ((icmp_ln284_reg_396[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign tmp_3_fu_177_p4 = {{pY_2[31:1]}};

assign tmp_4_fu_193_p4 = {{pX_2[31:1]}};

endmodule //myproject_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_12u_config2_s
