// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_ap_fixed_12u_array_ap_fixed_18_8_5_3_0_18u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer14_out_dout,
        layer14_out_num_data_valid,
        layer14_out_fifo_cap,
        layer14_out_empty_n,
        layer14_out_read,
        layer6_out_din,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_full_n,
        layer6_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [239:0] layer14_out_dout;
input  [9:0] layer14_out_num_data_valid;
input  [9:0] layer14_out_fifo_cap;
input   layer14_out_empty_n;
output   layer14_out_read;
output  [323:0] layer6_out_din;
input  [8:0] layer6_out_num_data_valid;
input  [8:0] layer6_out_fifo_cap;
input   layer6_out_full_n;
output   layer6_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer6_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer14_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln52_fu_668_p2;
wire   [19:0] trunc_ln58_fu_680_p1;
reg   [19:0] trunc_ln58_reg_821;
reg    ap_block_state2;
reg   [19:0] trunc_ln58_1_reg_826;
reg   [19:0] trunc_ln58_2_reg_831;
reg   [19:0] trunc_ln58_3_reg_836;
reg   [19:0] trunc_ln58_4_reg_841;
reg   [19:0] trunc_ln58_5_reg_846;
reg   [19:0] trunc_ln58_6_reg_851;
reg   [19:0] trunc_ln58_7_reg_856;
reg   [19:0] trunc_ln58_8_reg_861;
reg   [19:0] trunc_ln58_9_reg_866;
reg   [19:0] trunc_ln58_s_reg_871;
reg   [19:0] trunc_ln58_10_reg_876;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_ready;
wire   [323:0] grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_layer6_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_layer6_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start_reg;
reg    ap_block_state2_ignore_call15;
wire    ap_CS_fsm_state3;
reg   [8:0] indvar_flatten_fu_356;
wire   [8:0] add_ln52_fu_674_p2;
reg    ap_block_state1;
reg    layer14_out_read_local;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start_reg = 1'b0;
#0 indvar_flatten_fu_356 = 9'd0;
end

myproject_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_ready),
    .p_read(trunc_ln58_reg_821),
    .p_read1(trunc_ln58_1_reg_826),
    .p_read2(trunc_ln58_2_reg_831),
    .p_read3(trunc_ln58_3_reg_836),
    .p_read4(trunc_ln58_4_reg_841),
    .p_read5(trunc_ln58_5_reg_846),
    .p_read6(trunc_ln58_6_reg_851),
    .p_read7(trunc_ln58_7_reg_856),
    .p_read8(trunc_ln58_8_reg_861),
    .p_read9(trunc_ln58_9_reg_866),
    .p_read10(trunc_ln58_s_reg_871),
    .p_read11(trunc_ln58_10_reg_876),
    .layer6_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_layer6_out_din),
    .layer6_out_num_data_valid(9'd0),
    .layer6_out_fifo_cap(9'd0),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_layer6_out_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_668_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_ignore_call15) & (icmp_ln52_fu_668_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_356 <= 9'd0;
    end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_668_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_356 <= add_ln52_fu_674_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln58_10_reg_876 <= {{layer14_out_dout[239:220]}};
        trunc_ln58_1_reg_826 <= {{layer14_out_dout[39:20]}};
        trunc_ln58_2_reg_831 <= {{layer14_out_dout[59:40]}};
        trunc_ln58_3_reg_836 <= {{layer14_out_dout[79:60]}};
        trunc_ln58_4_reg_841 <= {{layer14_out_dout[99:80]}};
        trunc_ln58_5_reg_846 <= {{layer14_out_dout[119:100]}};
        trunc_ln58_6_reg_851 <= {{layer14_out_dout[139:120]}};
        trunc_ln58_7_reg_856 <= {{layer14_out_dout[159:140]}};
        trunc_ln58_8_reg_861 <= {{layer14_out_dout[179:160]}};
        trunc_ln58_9_reg_866 <= {{layer14_out_dout[199:180]}};
        trunc_ln58_reg_821 <= trunc_ln58_fu_680_p1;
        trunc_ln58_s_reg_871 <= {{layer14_out_dout[219:200]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_668_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_668_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_668_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer14_out_blk_n = layer14_out_empty_n;
    end else begin
        layer14_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_668_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer14_out_read_local = 1'b1;
    end else begin
        layer14_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer6_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_layer6_out_write;
    end else begin
        layer6_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_668_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_668_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_674_p2 = (indvar_flatten_fu_356 + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln52_fu_668_p2 == 1'd0) & (layer14_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call15 = ((icmp_ln52_fu_668_p2 == 1'd0) & (layer14_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_ap_start_reg;

assign icmp_ln52_fu_668_p2 = ((indvar_flatten_fu_356 == 9'd324) ? 1'b1 : 1'b0);

assign layer14_out_read = layer14_out_read_local;

assign layer6_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_18_8_5_3_0_18u_config6_s_fu_366_layer6_out_din;

assign start_out = real_start;

assign trunc_ln58_fu_680_p1 = layer14_out_dout[19:0];

endmodule //myproject_conv_2d_cl_array_ap_fixed_12u_array_ap_fixed_18_8_5_3_0_18u_config6_s
